name: branch

on:
  pull_request:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: sudo apt-get update && sudo apt-get install -y ca-certificates git

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15'

    - name: Checkout
      uses: actions/checkout@v2

      - name: Build
        run: |
          export GOPATH="${HOME}/go"
          export PATH="${GOPATH}/bin:${PATH}"
          VERSION=${GITHUB_REF##*/} make build-deps deps install test
          make fmt
          if [[ $(git status --short | grep -v package-lock) != '' ]]; then
            echo 'run make fmt and commit changes:'
            git diff --stat
            exit 1
          fi

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: ./coverage.txt
